name: Pull Request Body Validation

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  checks: write
  pull-requests: write

jobs:
  check-pr-body:
    runs-on: ubuntu-latest
    outputs:
      body_check_failed: ${{ steps.body_check.outputs.body_check_failed }}
    steps:
      - name: Check if the PR body contains 'Closes #'
        id: body_check
        run: |
          echo "BODY_CHECK_FAILED=false" >> $GITHUB_ENV
          if ! echo "${{ github.event.pull_request.body }}" | grep -iqE "Closes\s+#\d+"; then
            echo "BODY_CHECK_FAILED=true" >> $GITHUB_ENV
          fi

      - name: Comment on PR, if body check, fails
        if: ${{ env.BODY_CHECK_FAILED == 'true' }}
        uses: actions/github-script@v5
        with:
          script: |
            const issueComment = `Hello @${{ github.actor }} 👋, \
            \n\nIt looks like your PR description is missing 'Closes #'. \
            \nPlease include the phrase 'Closes #issue_ID' to indicate which issue this PR closes.`;
            github.rest.issues.createComment({
              issue_number: ${{ github.event.pull_request.number }},
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: issueComment
            });
            
      - name: Fail workflow if PR description is missing Closes #
        if: ${{ env.BODY_CHECK_FAILED == 'true' }}'
        run: |
          echo "Failing the workflow because PR description is missing Closes #."
          exit 1