name: Test with Coverage

on:
  pull_request:

permissions:
  checks: write
  pull-requests: write

env:
  CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}


jobs:
  test-cov:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install dependencies
        run: | 
          pip install --upgrade pip && pip install virtualenv && virtualenv .venv
          make install-flit && FLIT_ROOT_INSTALL=1 make install-dev
        
      - name: Run tests and collect coverage
        run: .venv/bin/python pytest --cov --cov-report=xml

      - name: Install Codecov
        run: curl -Os https://cli.codecov.io/latest/linux/codecov && chmod +x codecov

      - name: Upload coverage to Codecov
        run: ./codecov upload-process --git-service github --file ./coverage.xml --commit-sha ${{ github.event.pull_request.head.sha }}